# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sound_window_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Sound processing")
        Form.resize(269, 550)
        Form.setMinimumSize(QtCore.QSize(269, 550))
        Form.setMaximumSize(QtCore.QSize(269, 550))
        Form.setStyleSheet("background-color: rgb(121, 134, 134);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 300, 101, 51))
        self.pushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 300, 101, 51))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 360, 211, 51))
        self.pushButton_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 480, 211, 51))
        self.pushButton_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 420, 101, 51))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 420, 101, 51))
        self.pushButton_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(163, 197, 200);\n"
"border-radius: 7px;\n"
"border: 2px solid rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 17, 221, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox.setStyleSheet("")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_16.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_16)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_20.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_17.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(30, 260, 221, 31))
        self.label_21.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_21.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Generate"))
        self.pushButton_2.setText(_translate("Form", "Show pure \n"
"waves"))
        self.pushButton_3.setText(_translate("Form", "Save pure waves"))
        self.pushButton_6.setText(_translate("Form", "Save noise \n"
"waves"))
        self.pushButton_5.setText(_translate("Form", "Show noise \n"
"waves"))
        self.pushButton_4.setText(_translate("Form", "Add noise"))
        self.label.setText(_translate("Form", "Duration"))
        self.label_2.setText(_translate("Form", "Sampling rate"))
        self.label_3.setText(_translate("Form", "Num samples"))
        self.label_6.setText(_translate("Form", "Сomplicate data"))
        self.label_4.setText(_translate("Form", "Num visualize"))
        self.label_5.setText(_translate("Form", "Noise coefficient"))
        self.label_19.setText(_translate("Form", "Name pure file"))
        self.label_20.setText(_translate("Form", "Name noise file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
